language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
    - libboost-all-dev
env:
  - CXX=g++-9
install:
  - git submodule sync
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
script:
  - cd code || echo "already in code"
  - make coreset_test btest kmpptest graphtest
  - ./coreset_test
  - ./btest
  - ./kmpptest
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
